disabled_rules:
 - trailing_whitespace
 - identifier_name #for JSON
 - empty_enum_arguments #for error data tasks
 - multiple_closures_with_trailing_closure #for animation
type_name:
 allowed_symbols: ["_"]
line_length:
 - 300 # warning
 - 400 # error
